#!/usr/bin/ruby

# This script is used to kick off an internal developer build.
# To get a full tagged release, instead see the README_release.txt.
#
`git remote update`
`git checkout master`
`git pull origin master`

x = `git describe` # Looks like "1.6.4r-17-g65d9478"

parts = x.split('-')

y = "#{parts[0]}-#{parts[1].to_i + 1}"

File.open('CHANGES', 'w') {|o| o.write("for " + y)}

`git add CHANGES`
`git commit -m "MARKED for #{y}"`
`git push gerrit HEAD:refs/for/master`



